FROM ubuntu:24.04
RUN apt-get update \
&& apt-get dist-upgrade -y \
&& apt-get autoremove -y \
&& apt-get autoclean -y \
&& apt-get install -y \
sudo \
nano \
wget \
curl \
git

RUN useradd -G sudo -m -d /home/ole -s /bin/bash -p "$(openssl passwd -1 1234)" ole

RUN mkdir hacking \
&& cd hacking \
&& curl -SL https://raw.githubusercontent.com/uia-worker/is105misc/master/sem01v24/pawned.sh > pawned.sh \
&& chmod 764 pawned.sh \
&& cd ..

RUN git config --global user.email "user.email"
RUN git config --global user.name "user.name"
RUN git config --global url."https://pam:@github.com/".insteadOf"https://github.com"
RUN mkdir -p github.com/uia-worker

USER root
RUN curl -SL https://go.dev/dl/go1.21.7.linux-amd64.tar.gz \
| tar xvz -C /usr/local
USER BRUKER
SHELL ["/bin/bash", "-c"]
RUN mkdir -p $HOME/go/{src,bin}
ENV GOPATH="/home/ole/go"
ENV PATH="${PATH}:${GOPATH}/bin:/usr/local/go/bin"